import { bold, cyan, dim, yellow } from '../render/ansi.js';
import { brandTitle, frameBlock } from '../tui/frame.js';
import type { CommandSpec } from './args.js';
import { COMMANDS, GLOBAL_FLAGS } from './spec.js';

/**
 * Frame help only when a person is going to read it.
 *
 * Piped output ends up in an agent's context or in a file, and box-drawing
 * characters there are noise wrapped around the only part that matters.
 */
function forPerson(lines: string[], version?: string): string {
  if (!process.stdout.isTTY) return lines.join('\n');
  return frameBlock(lines, { title: brandTitle(version) });
}

/**
 * Sections, in the order someone reading this needs them.
 *
 * Most of these commands exist for an agent to call. Listing all twenty flat
 * made the handful a person actually types impossible to pick out, so the ones
 * you run by hand come first and the rest are labelled for what they are.
 */
const GROUPS: Array<{ key: 'common' | 'agent' | 'maintenance'; title: string }> = [
  { key: 'common', title: 'Everyday' },
  { key: 'agent', title: 'Run by your agent' },
  { key: 'maintenance', title: 'Housekeeping' },
];

export function topLevelHelp(version: string): string {
  const out: string[] = [
    `${bold('planx')} ${dim(version)} — plan capture, review and locking`,
    '',
    `  ${dim('planx')}                    review a plan`,
    `  ${dim('planx <plan> [version]')}   review that plan`,
    `  ${dim('planx <command> [args]')}`,
    '',
  ];

  const visible = COMMANDS.filter((c) => !c.hidden);
  const width = Math.max(...visible.map((c) => c.name.length));

  for (const group of GROUPS) {
    const members = visible.filter((c) => (c.group ?? 'maintenance') === group.key);
    if (!members.length) continue;
    out.push(dim(`  ${group.title}:`));
    for (const command of members) {
      out.push(`  ${cyan(command.name.padEnd(width))}  ${command.summary}`);
    }
    out.push('');
  }

  out.push(dim('  Global flags:'));
  for (const flag of GLOBAL_FLAGS) {
    out.push(`  ${yellow(flagLabel(flag.name, flag.arg).padEnd(width + 2))}  ${dim(flag.summary)}`);
  }
  out.push('', dim('  planx <command> --help for detail.'));
  return forPerson(out, version);
}

export function commandHelp(spec: CommandSpec, version?: string): string {
  const out: string[] = [`${bold(spec.name)} — ${spec.summary}`, '', `  ${dim(spec.usage)}`];

  if (spec.description) {
    out.push('', ...wrap(spec.description, 76).map((line) => `  ${line}`));
  }
  if (spec.flags?.length) {
    out.push('');
    const width = Math.max(...spec.flags.map((f) => flagLabel(f.name, f.arg).length));
    for (const flag of spec.flags) {
      out.push(`  ${yellow(flagLabel(flag.name, flag.arg).padEnd(width))}  ${dim(flag.summary)}`);
    }
  }
  if (spec.examples?.length) {
    out.push('', dim('  Examples:'));
    for (const example of spec.examples) out.push(`    ${example}`);
  }
  return forPerson(out, version);
}

function flagLabel(name: string, arg?: string): string {
  return arg ? `${name} <${arg}>` : name;
}

/**
 * Generate `site/reference/cli.md` from the same specs `--help` reads.
 *
 * Hand-maintained CLI docs go stale within two releases, without exception, so
 * this runs in CI and the result is committed.
 */
export function generateReference(version: string): string {
  const out: string[] = [
    '<!--',
    '  Generated by `planx __gen-cli-docs` from src/cli/spec.ts.',
    '  Do not edit by hand — edit the spec and re-run `npm run docs:cli`.',
    '-->',
    '',
    '# CLI reference',
    '',
    `Generated from planx ${version}.`,
    '',
    '## Global flags',
    '',
    '| Flag | Meaning |',
    '| --- | --- |',
  ];

  for (const flag of GLOBAL_FLAGS) {
    out.push(`| \`${flagLabel(flag.name, flag.arg)}\` | ${escapeCell(flag.summary)} |`);
  }
  out.push('');
  out.push('`NO_COLOR` is honoured, and `PLANX_DIR` sets the store the same way `--dir` does.');
  out.push('');

  for (const command of COMMANDS) {
    if (command.hidden) continue;
    out.push(`## \`planx ${command.name}\``, '');
    out.push(command.summary, '');
    out.push('```', command.usage, '```', '');
    if (command.description) out.push(command.description, '');
    if (command.flags?.length) {
      out.push('| Flag | Meaning |', '| --- | --- |');
      for (const flag of command.flags) {
        out.push(`| \`${flagLabel(flag.name, flag.arg)}\` | ${escapeCell(flag.summary)} |`);
      }
      out.push('');
    }
    if (command.examples?.length) {
      out.push('```bash', ...command.examples, '```', '');
    }
  }

  return out.join('\n');
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function wrap(text: string, width: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    if (current.length + word.length + 1 > width) {
      lines.push(current);
      current = word;
    } else {
      current = current ? `${current} ${word}` : word;
    }
  }
  if (current) lines.push(current);
  return lines;
}
