import { bold, cyan, dim, yellow } from '../render/ansi.js';
import type { CommandSpec } from './args.js';
import { COMMANDS, GLOBAL_FLAGS } from './spec.js';

export function topLevelHelp(version: string): string {
  const out: string[] = [
    `${bold('planx')} ${dim(version)} — plan capture, review, locking and execution`,
    '',
    `  ${dim('planx <command> [args]')}`,
    '',
  ];

  const width = Math.max(...COMMANDS.filter((c) => !c.hidden).map((c) => c.name.length));
  for (const command of COMMANDS) {
    if (command.hidden) continue;
    out.push(`  ${cyan(command.name.padEnd(width))}  ${command.summary}`);
  }

  out.push('', dim('  Global flags:'));
  for (const flag of GLOBAL_FLAGS) {
    out.push(`  ${yellow(flagLabel(flag.name, flag.arg).padEnd(width + 2))}  ${dim(flag.summary)}`);
  }
  out.push('', dim('  planx <command> --help for detail.'));
  return out.join('\n');
}

export function commandHelp(spec: CommandSpec): string {
  const out: string[] = [`${bold(spec.name)} — ${spec.summary}`, '', `  ${dim(spec.usage)}`];

  if (spec.description) {
    out.push('', ...wrap(spec.description, 76).map((line) => `  ${line}`));
  }
  if (spec.flags?.length) {
    out.push('');
    const width = Math.max(...spec.flags.map((f) => flagLabel(f.name, f.arg).length));
    for (const flag of spec.flags) {
      out.push(`  ${yellow(flagLabel(flag.name, flag.arg).padEnd(width))}  ${dim(flag.summary)}`);
    }
  }
  if (spec.examples?.length) {
    out.push('', dim('  Examples:'));
    for (const example of spec.examples) out.push(`    ${example}`);
  }
  return out.join('\n');
}

function flagLabel(name: string, arg?: string): string {
  return arg ? `${name} <${arg}>` : name;
}

/**
 * Generate `site/reference/cli.md` from the same specs `--help` reads.
 *
 * Hand-maintained CLI docs go stale within two releases, without exception, so
 * this runs in CI and the result is committed (PLAN §15).
 */
export function generateReference(version: string): string {
  const out: string[] = [
    '<!--',
    '  Generated by `planx __gen-cli-docs` from src/cli/spec.ts.',
    '  Do not edit by hand — edit the spec and re-run `npm run docs:cli`.',
    '-->',
    '',
    '# CLI reference',
    '',
    `Generated from planx ${version}.`,
    '',
    '## Global flags',
    '',
    '| Flag | Meaning |',
    '| --- | --- |',
  ];

  for (const flag of GLOBAL_FLAGS) {
    out.push(`| \`${flagLabel(flag.name, flag.arg)}\` | ${escapeCell(flag.summary)} |`);
  }
  out.push('');
  out.push('`NO_COLOR` is honoured, and `PLANX_DIR` sets the store the same way `--dir` does.');
  out.push('');

  for (const command of COMMANDS) {
    if (command.hidden) continue;
    out.push(`## \`planx ${command.name}\``, '');
    out.push(command.summary, '');
    out.push('```', command.usage, '```', '');
    if (command.description) out.push(command.description, '');
    if (command.flags?.length) {
      out.push('| Flag | Meaning |', '| --- | --- |');
      for (const flag of command.flags) {
        out.push(`| \`${flagLabel(flag.name, flag.arg)}\` | ${escapeCell(flag.summary)} |`);
      }
      out.push('');
    }
    if (command.examples?.length) {
      out.push('```bash', ...command.examples, '```', '');
    }
  }

  return out.join('\n');
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function wrap(text: string, width: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    if (current.length + word.length + 1 > width) {
      lines.push(current);
      current = word;
    } else {
      current = current ? `${current} ${word}` : word;
    }
  }
  if (current) lines.push(current);
  return lines;
}
